r1_teleop:
  double_click_minimum_interval: 0.0
  double_click_maximum_interval: 0.2
  max_linear_x_velocity: 1.0
  max_linear_y_velocity: 1.0
  max_angular_z_velocity: 3.0
  boost_velocity_ratio: 1.0
  joy_topic: joy
  timer_frequency: 20.0
  servo_increment: 3 # 60°/sec at 20Hz